### ISSUE TITLE
annotations of live video feed

### ISSUE THREAD

**Issue by sujeetsingh007** [opentok/one-to-one-screen-annotations-sample-apps#112]
Hi,
I am looking for a sample app for annotations on live video stream.Please help

**Comment by marinaserranomontes** [comment]
Hi @sujeetsingh007 
Now, we are working on video annotations samples. These are in progress. You can find info in the following repo: https://github.com/opentok/video-annotation-acc-pack

**Comment by Lucashuang0802** [comment]
@sujeetsingh007 For your information, https://github.com/opentok/video-annotation-acc-pack will be provided as a sample for how to use annotation accelerator pack(annotation accelerator pack (https://github.com/opentok/annotation-acc-pack).
