### ISSUE TITLE
OTKAnalytics, OTSolution are not defined

### ISSUE THREAD

**Issue by voltrevo** [opentok/one-to-one-screen-annotations-sample-apps#118]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/opentok/screensharing-annotation-acc-pack/blob/develop/README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/screensharing-annotation-acc-pack/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Acreated-desc+) and **this is not a duplicate**.

### General information

- Library version(s): opentok.js production, this project's master
- iOS/Android/Browser version(s): Chrome 54
- Devices/Simulators/Machine affected: Mac OS
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

#### Expected behavior

`OTKAnalytics` is defined
`OTSolution` is defined

#### Actual behavior

Exception is thrown indicating `OTKAnalytics` is not defined
Exception is thrown indicating `OTSolution` is not defined

#### Steps to reproduce

Run the sample app. For the `OTSolution` error, also delete all the analytics code and try to start screensharing (otherwise the code execution doesn't get a chance to get to this point).

#### Crash log? Screenshots? Videos? Sample project?

![screen shot 2016-10-26 at 6 02 42 pm](https://cloud.githubusercontent.com/assets/9291586/19716243/70740d0c-9ba6-11e6-8f1f-8471ec853077.png)

![screen shot 2016-10-26 at 5 58 56 pm](https://cloud.githubusercontent.com/assets/9291586/19716156/eb401cfc-9ba5-11e6-8d28-e7e9143087ee.png)

**Comment by adrice727** [comment]
@voltrevo See my comment about the `build` script [here](https://github.com/opentok/one-to-one-screen-annotations-sample-apps/pull/117).  Does this fix the issue?

**Comment by voltrevo** [comment]
@adrice727 Yep.
